import { DashboardMetrics, IATFLot, LotAnimal, ManagementEvent, SemenBatch, Bull, Protocol } from './types/iatf';

export const INITIAL_METRICS: DashboardMetrics = {
  total_animals: 892,
  active_lots: 7,
  total_inseminations: 865,
  total_diagnoses: 865,
  total_pregnancies: 512,
  overall_pregnancy_rate: 59.19, // 512 / 865 * 100
  total_device_losses: 14,
  pending_managements: 2,
};

export const INITIAL_LOTS: IATFLot[] = [
  {
    id: 'lot-1',
    code: 'LOTE 01',
    farm_name: 'BOI GORDO',
    property_name: 'RETIRO 01',
    protocol_name: 'PROTOCOLO 01 (3 MANEJOS)',
    start_date: '2025-09-10',
    ia_date: '2025-09-19',
    dg_date: '2025-10-24',
    planned_qty: 120,
    worked_qty: 118,
    inseminated_qty: 115,
    pregnancies: 68,
    empty: 47,
    pregnancy_rate: 59.13,
    responsible: 'DR. SAMOEL DUARTE',
    status: 'concluido',
  },
  {
    id: 'lot-2',
    code: 'LOTE 02',
    farm_name: 'BOI GORDO',
    property_name: 'RETIRO 01',
    protocol_name: 'PROTOCOLO 01 (3 MANEJOS)',
    start_date: '2025-09-24',
    ia_date: '2025-10-03',
    dg_date: '2025-11-07',
    planned_qty: 140,
    worked_qty: 138,
    inseminated_qty: 135,
    pregnancies: 82,
    empty: 53,
    pregnancy_rate: 60.74,
    responsible: 'DR. SAMOEL DUARTE',
    status: 'concluido',
  },
  {
    id: 'lot-3',
    code: 'LOTE 03',
    farm_name: 'BOI GORDO',
    property_name: 'RETIRO 02',
    protocol_name: 'PROTOCOLO 02 (RESSIA)',
    start_date: '2025-10-08',
    ia_date: '2025-10-17',
    dg_date: '2025-11-21',
    planned_qty: 110,
    worked_qty: 108,
    inseminated_qty: 106,
    pregnancies: 61,
    empty: 45,
    pregnancy_rate: 57.55,
    responsible: 'DR. SAMOEL DUARTE',
    status: 'concluido',
  },
  {
    id: 'lot-4',
    code: 'LOTE 04',
    farm_name: 'BOI GORDO',
    property_name: 'RETIRO 02',
    protocol_name: 'PROTOCOLO 01 (3 MANEJOS)',
    start_date: '2025-10-22',
    ia_date: '2025-10-31',
    dg_date: '2025-12-05',
    planned_qty: 150,
    worked_qty: 146,
    inseminated_qty: 142,
    pregnancies: 88,
    empty: 54,
    pregnancy_rate: 61.97,
    responsible: 'MV. JOÃO SILVA',
    status: 'concluido',
  },
  {
    id: 'lot-5',
    code: 'LOTE 05',
    farm_name: 'BOI GORDO',
    property_name: 'RETIRO 03',
    protocol_name: 'PROTOCOLO 01 (3 MANEJOS)',
    start_date: '2025-11-05',
    ia_date: '2025-11-14',
    dg_date: '2025-12-19',
    planned_qty: 130,
    worked_qty: 127,
    inseminated_qty: 125,
    pregnancies: 71,
    empty: 54,
    pregnancy_rate: 56.80,
    responsible: 'MV. JOÃO SILVA',
    status: 'concluido',
  },
  {
    id: 'lot-6',
    code: 'LOTE 06',
    farm_name: 'BOI GORDO',
    property_name: 'RETIRO 03',
    protocol_name: 'PROTOCOLO 01 (3 MANEJOS)',
    start_date: '2025-11-19',
    ia_date: '2025-11-28',
    dg_date: '2026-01-09',
    planned_qty: 125,
    worked_qty: 124,
    inseminated_qty: 120,
    pregnancies: 69,
    empty: 51,
    pregnancy_rate: 57.50,
    responsible: 'DR. SAMOEL DUARTE',
    status: 'concluido',
  },
  {
    id: 'lot-7',
    code: 'LOTE 07',
    farm_name: 'BOI GORDO',
    property_name: 'RETIRO 01',
    protocol_name: 'PROTOCOLO 01 (3 MANEJOS)',
    start_date: '2025-12-03',
    ia_date: '2025-12-12',
    dg_date: '2026-01-23',
    planned_qty: 127,
    worked_qty: 125,
    inseminated_qty: 122,
    pregnancies: 73,
    empty: 49,
    pregnancy_rate: 59.84,
    responsible: 'DR. SAMOEL DUARTE',
    status: 'concluido',
  },
];

export const INITIAL_BULLS: Bull[] = [
  { id: 'b1', name: 'NELORE BARRANCO 4501', code: 'NEL-4501', breed: 'Nelore', owner_central: 'CRV Lagoa' },
  { id: 'b2', name: 'ANGUS BLACK EDITION', code: 'ANG-901', breed: 'Angus', owner_central: 'ABS Pecplan' },
  { id: 'b3', name: 'BRANGUS IMPERIAL 78', code: 'BRG-078', breed: 'Brangus', owner_central: 'Alta Genetics' },
  { id: 'b4', name: 'SENEPOL REMO 12', code: 'SEN-012', breed: 'Senepol', owner_central: 'Select Sires' },
];

export const INITIAL_SEMEN_BATCHES: SemenBatch[] = [
  { id: 's1', bull_id: 'b1', bull_name: 'NELORE BARRANCO 4501', batch_number: 'P-2025A', initial_quantity: 500, used_quantity: 340, lost_quantity: 5, current_stock: 155 },
  { id: 's2', bull_id: 'b2', bull_name: 'ANGUS BLACK EDITION', batch_number: 'P-901B', initial_quantity: 400, used_quantity: 280, lost_quantity: 3, current_stock: 117 },
  { id: 's3', bull_id: 'b3', bull_name: 'BRANGUS IMPERIAL 78', batch_number: 'P-078C', initial_quantity: 300, used_quantity: 210, lost_quantity: 2, current_stock: 88 },
  { id: 's4', bull_id: 'b4', bull_name: 'SENEPOL REMO 12', batch_number: 'P-012D', initial_quantity: 100, used_quantity: 35, lost_quantity: 0, current_stock: 65 },
];

export const INITIAL_PROTOCOLS: Protocol[] = [
  {
    id: 'p1',
    name: 'PROTOCOLO 01 (3 MANEJOS)',
    description: 'Protocolo tradicional com Benzoato no D0, PGF no D7, eCG + Cipionato no D9 e IA em 48h.',
    steps: [
      { code: 'D0', name: 'Aplicação BE + Implante P4', day_offset: 0, instruction: '2,0 ml BE + Colocação Implante P4' },
      { code: 'D7', name: 'Aplicação PGF2a', day_offset: 7, instruction: '2,0 ml PGF2a Cloprostenol' },
      { code: 'D9', name: 'Retirada Implante + eCG + Cipionato', day_offset: 9, instruction: '1,5 ml eCG + 0,5 ml Cipionato + Retirada P4' },
      { code: 'IA', name: 'Inseminação Artificial', day_offset: 11, instruction: 'Inseminar 48h a 54h após retirada do implante' },
      { code: 'DG', name: 'Diagnóstico de Gestação', day_offset: 44, instruction: 'Ultrassonografia (30 a 35 dias pós IA)' },
    ],
  },
  {
    id: 'p2',
    name: 'PROTOCOLO 02 (RESSIA)',
    description: 'Protocolo de ressicronização precoce para vacas vazias.',
    steps: [
      { code: 'D0', name: 'Implante P4 + BE', day_offset: 0, instruction: '1,0 ml BE + Implante P4 Reaproveitado' },
      { code: 'D8', name: 'Retirada P4 + PGF + eCG + EC', day_offset: 8, instruction: '2,0 ml PGF + 1,5 ml eCG + 0,5 ml EC + Retirada' },
      { code: 'IA', name: 'Inseminação Artificial', day_offset: 10, instruction: 'Inseminar 48h pós retirada' },
      { code: 'DG', name: 'Diagnóstico de Gestação', day_offset: 40, instruction: 'Ultrassonografia' },
    ],
  },
];

export const INITIAL_MANAGEMENT_EVENTS: ManagementEvent[] = [
  {
    id: 'm1',
    lot_code: 'LOTE 01',
    step_code: 'D0',
    step_name: 'Aplicação de Benzoato e Colocação de Implante',
    planned_date: '2025-09-10',
    execution_date: '2025-09-10',
    start_time: '07:00',
    end_time: '10:30',
    animals_worked: 118,
    responsible: 'DR. SAMOEL DUARTE',
    status: 'concluido',
  },
  {
    id: 'm2',
    lot_code: 'LOTE 01',
    step_code: 'IA',
    step_name: 'Inseminação Artificial em Tempo Fixo',
    planned_date: '2025-09-19',
    execution_date: '2025-09-19',
    start_time: '06:30',
    end_time: '11:45',
    animals_worked: 115,
    responsible: 'DR. SAMOEL DUARTE',
    status: 'concluido',
  },
  {
    id: 'm3',
    lot_code: 'LOTE 01',
    step_code: 'DG',
    step_name: 'Diagnóstico de Gestação (Ultrassom)',
    planned_date: '2025-10-24',
    execution_date: '2025-10-24',
    start_time: '07:30',
    end_time: '11:00',
    animals_worked: 115,
    responsible: 'DR. SAMOEL DUARTE',
    status: 'concluido',
  },
  {
    id: 'm4',
    lot_code: 'LOTE 08 (NOVO)',
    step_code: 'D0',
    step_name: 'Aplicação BE + Inserção de Implante P4',
    planned_date: '2026-08-14',
    responsible: 'DR. SAMOEL DUARTE',
    animals_worked: 0,
    status: 'proximo',
  },
  {
    id: 'm5',
    lot_code: 'LOTE 08 (NOVO)',
    step_code: 'D7',
    step_name: 'Aplicação de PGF2a',
    planned_date: '2026-08-21',
    responsible: 'MV. JOÃO SILVA',
    animals_worked: 0,
    status: 'proximo',
  },
];

export const MOCK_ANIMALS_LOTE01: LotAnimal[] = [
  { id: 'a1', tag_number: '1001', category: 'Multípara', breed: 'Nelore', ecc_ia: 3.00, bull_name: 'NELORE BARRANCO 4501', semen_batch: 'P-2025A', inseminator: 'JOÃO SILVA', pregnancy_status: 'Prenha', ecc_dg: 3.25, expected_parturition: '2026-07-01' },
  { id: 'a2', tag_number: '1002', category: 'Novilha', breed: 'Nelore', ecc_ia: 2.75, bull_name: 'ANGUS BLACK EDITION', semen_batch: 'P-901B', inseminator: 'JOÃO SILVA', pregnancy_status: 'Prenha', ecc_dg: 3.00, expected_parturition: '2026-07-01' },
  { id: 'a3', tag_number: '1003', category: 'Primípara', breed: 'Nelore', ecc_ia: 2.50, bull_name: 'NELORE BARRANCO 4501', semen_batch: 'P-2025A', inseminator: 'PEDRO SANTOS', pregnancy_status: 'Vazia', ecc_dg: 2.50 },
  { id: 'a4', tag_number: '1004', category: 'Multípara', breed: 'Nelore', ecc_ia: 3.25, bull_name: 'BRANGUS IMPERIAL 78', semen_batch: 'P-078C', inseminator: 'PEDRO SANTOS', pregnancy_status: 'Prenha', ecc_dg: 3.50, expected_parturition: '2026-07-01' },
  { id: 'a5', tag_number: '1005', category: 'Secundípara', breed: 'Nelore', ecc_ia: 2.75, bull_name: 'NELORE BARRANCO 4501', semen_batch: 'P-2025A', inseminator: 'JOÃO SILVA', pregnancy_status: 'Prenha', ecc_dg: 3.00, expected_parturition: '2026-07-01' },
  { id: 'a6', tag_number: '1006', category: 'Novilha', breed: 'Nelore', ecc_ia: 2.25, bull_name: 'ANGUS BLACK EDITION', semen_batch: 'P-901B', inseminator: 'JOÃO SILVA', pregnancy_status: 'Vazia', ecc_dg: 2.50 },
  { id: 'a7', tag_number: '1007', category: 'Multípara', breed: 'Nelore', ecc_ia: 3.00, bull_name: 'NELORE BARRANCO 4501', semen_batch: 'P-2025A', inseminator: 'PEDRO SANTOS', pregnancy_status: 'Prenha', ecc_dg: 3.25, expected_parturition: '2026-07-01' },
  { id: 'a8', tag_number: '1008', category: 'Primípara', breed: 'Nelore', ecc_ia: 2.75, bull_name: 'BRANGUS IMPERIAL 78', semen_batch: 'P-078C', inseminator: 'JOÃO SILVA', pregnancy_status: 'Prenha', ecc_dg: 3.00, expected_parturition: '2026-07-01' },
];
